# Copyright 2023 the Lig authors. All rights reserved. MIT license.

[package]
name = "lig_core"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The Lig database library"

[lib]
name = "lig_core"
path = "lib.rs"

[dependencies]
anyhow = "1.0.75"
fallible-iterator = "0.3.0"
sqlite3-parser = "0.11.0"
